
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 3 # Number of replicas
  selector:
    matchLabels:
      app: myapp-v1
  template:
    metadata:
      labels:
        app: myapp-v1
    spec:
      containers:
        - name: myapp-v1
          image: kundhana/argocd:v1
          ports:
            - containerPort: 8080  # Port 8080
